# Generated by Django 5.2.6 on 2025-09-17 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_enrollment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
